baseURL = "https://nitingarg.me"
languageCode = "en-us"
title = "Nitin Garg"
theme = "osprey"

[Params]
    tagline = "Software and Hardware Engineering"
    logoBig = "/images/logo.png"
    logoSmall = "/images/logo.png"
    github = "nitgarg99"
    linkedin = "nitgarg99"
    twitter = "nitgarg99"
    email = "nitgarg99@gmail.com"
    ajaxFormspree = true
    

[[menu.main]]
    name = "About"
    url = "/#about"
    weight = 1
[[menu.main]]
    name = "Work"
    url = "/#work"
    weight = 2
[[menu.main]]
    name = "Blog"
    url = "/#blog"
    weight = 3
[[menu.main]]
    name = "Contact"
    url = "/#contact"
    weight = 4
